### ISSUE TITLE
Plainly not working?

### ISSUE THREAD

**Issue by TheChymera** [robbyedwards/octopress-tag-cloud#4]
Hi guys, is this still maintained?

I just downlooaded this and [octopress-tag-pages](https://github.com/robbyedwards/octopress-tag-pages), and copied their `tag_generator.rb` in the `/plugins` folder; then added the `tag_index.html` file to `/source/_layouts`. Then I added your  `tag_cloud.rb` in the `/plugins` folder.

Finally, I created a new page under `/source/new_page/index.markdown` containing:

```

---
layout: page
title: "tag cloud"
date: 2014-10-13 07:47
author: Horea Christian
comments: true
sharing: true
footer: true

---

{% tag_cloud %}
```

The page is empty. What's wrong?

**Comment by csutherl** [comment]
@TheChymera It doesn't look like it is :( The last update was ~2 years ago and I've had a PR open since March. I haven't used it since then, but it was working for me then...

**Comment by TheChymera** [comment]
Interested in setting up a new tag list generator? I'm wondering whether this can just be done as part of a theme (rather than creating an extra plugin) - jeckyll offers some nice variables to list tags and catergories - I'm just unsure how we could get a font size contingent on the number of said tag/category instances...
